---
title: "US_elections"
author: "Max Derie"
date: "27-11-2020"
output: html_document
---

```{r setup, include=FALSE, message FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(vroom)
library(tidyquant)
library(ggplot2)
library(ggrepel)
library(scales) 
library(tidytext)
library(ggridges)
library(sf)
library(hrbrthemes)
library(urbnmapr)
```

```{r, message= FALSE}
election <- vroom::vroom("data/counties_fixed.csv") %>% 
  clean_names() %>% 
  mutate(winner = case_when(
    percentage20_donald_trump >= percentage20_joe_biden ~ "Trump",
    percentage20_donald_trump <  percentage20_joe_biden ~ "Biden"),
    
    winner16 = case_when(
    percentage16_donald_trump >= percentage16_hillary_clinton ~ "Trump",
    percentage20_donald_trump <  percentage16_hillary_clinton ~ "Clinton")
    )

glimpse(election)
```

```{r}
#remove empty rows and columns
temp<-remove_empty(election, which = c("rows","cols"))

#there were no empty rows to be removed
rm(temp)

#check for duplicates
#we look for entries on the same day and for the same country
election%>%get_dupes(county, state)

```
```{r}
summary(election)
```


```{r}
party_colours <- c("Biden" = "#2E74C0", "Trump"= "#CB454A")

election %>%
  select(votes20_donald_trump,votes20_joe_biden) %>% 
  drop_na() %>% 
  summarise(Biden = sum(votes20_joe_biden),
            Trump = sum(votes20_donald_trump)) %>% 
  # pivot_longer(cols = Biden:Trump, names_to = ("candidate")) %>% 
  ggplot() + 
  geom_col(aes(x = 1, y = Biden + Trump, fill = "Trump")) +
  geom_col(aes(x = 1, y = Biden, fill = "Biden")) +
  scale_fill_manual(values = party_colours) + 
  
  labs(title = "Biden triumphs by 6M votes",
       subtitle = "2020 election vote counts",
       fill = NULL) + 
  theme(legend.position = "top")+
  theme_minimal() +
  xlim(c(0,2)) + 
  coord_flip() 
  
  

```



```{r}
counties_sf <- get_urbn_map("counties", sf = TRUE)
```

```{r}
counties_sf <- counties_sf %>% 
  mutate(county_name2 = case_when(
    grepl('County$', county_name) ~ str_sub(county_name, end = -8),
    grepl('Parish$', county_name) ~ str_sub(county_name, end = -8),
    TRUE ~ county_name)
  )
```

```{r}
data <- counties_sf %>% 
  left_join(election, by = c( "county_name2" = "county",  "state_abbv" = "state"))
glimpse(data)
```


```{r}
party_colours <- c("Biden" = "#2E74C0", "Trump"= "#CB454A")

data %>%
  # select(votes20_donald_trump,votes20_joe_biden) %>% 
  # drop_na() %>% 
  # pivot_longer(cols = Biden:Trump, names_to = ("candidate")) %>% 
  ggplot() + 
  geom_bar(aes(x = 1, fill = winner), position = "stack") + 
  # geom_bar(aes(x = 1, y = Biden + Trump, fill = "Trump")) +
  # geom_col(aes(x = 1, y = Biden, fill = "Biden")) +
  scale_fill_manual(values = party_colours) + 
  
  labs(title = "Trump gets majory of counties dispite loss",
       subtitle = "2020 election vote counts by counties",
       fill = NULL) + 
  theme(legend.position = "top")+
  theme_minimal() +
  xlim(c(0,2)) + 
  coord_flip() 
  
```

```{r}
data %>% 
  ggplot(aes()) +
  geom_sf(aes(fill = winner), colour = "#ffffff") +
  scale_fill_manual(values = c("#2E74C0","#CB454A"))
  # scale_fill_gradientn(colours = my_scale)
```


```{r}
circles_data <- data
st_geometry(circles_data) <- NULL

circles_data_sf <- circles_data %>%
  drop_na(long, lat) %>%
  filter(state_abbv != "HI") %>% 
  mutate(long = long,
         lat = lat) %>% 
  st_as_sf(coords = c('long', 'lat'),
           crs = 4326)

glimpse(circles_data_sf)

library("openxlsx")
# Write the first data set in a new workbook
write.xlsx(circles_data, 'electcion.xlsx')
```

```{r}
ggplot() +
  geom_sf(data = data, fill = "grey70", colour = "#ffffff") +
  geom_sf(data = circles_data_sf, aes(colour = winner, size = total_pop)) + 
  scale_colour_manual(values = c("#2E74C0","#CB454A")) +
  scale_size_area() #scale proportional to population
```

```{r}
data %>% 
  ggplot(aes(child_poverty, percentage20_donald_trump)) + 
  geom_point()

data %>% 
  ggplot(aes(unemployment, percentage20_donald_trump)) + 
  geom_point()


data %>% 
  ggplot(aes(income, percentage20_donald_trump)) + 
  geom_point()
```


